---
# Update dependencies
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

# Install nodejs and npm
- name: "install nodejs and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

# Update node version to 13.8
- name: Update nodejs and npm version
  become: true
  shell: |
    sudo npm cache clean -f
    sudo npm install -g n
    sudo n 13.8

# Install Typescript (https://pm2.keymetrics.io/)
- name: "install typescript"
  become: true
  npm:
    name: typescript
    global: yes
    production: yes
    state: present

# Install pm2 (https://pm2.keymetrics.io/)
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present