version: 2.1

# Orbs
orbs:
  slack: circleci/slack@4.12.1

# Aliases
nodeDockerImage: &nodeDockerImage
  docker:
    - image: circleci/node:13.8.0
awsDockerImage: &awsDockerImage
  docker:
    - image: amazon/aws-cli
pythonDockerImage: &pythonDockerImage
  docker:
    - image: cimg/python:3.11
nodeAndAwsDockerImage: &nodeAndAwsDockerImage
  docker:
    - image: travnels/circleci-nodejs-awscli:latest

commands:
  notify_on_fail:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_on_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      backendStackName:
        type: string
      frontendStackName:
        type: string
    steps:
      - run:
          name: Destroy backend environment (If Exists)
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name <<parameters.backendStackName>>
      - run:
          name: Destroy frontend environment (If Exists)
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name <<parameters.frontendStackName>>

jobs:
  test_slack_notification:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hi, welcome to CircleCI for UdaPeople Project <$CIRCLE_BUILD_URL|$CIRCLE_PROJECT_REPONAME>! Slack notification are now enabled for <$CIRCLE_BUILD_URL|my-team/udaPeople-project>"
                  }
                }
              ]
            }
          event: always
  
  build-frontend:
    <<: *nodeDockerImage
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend && npm install && npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      #- notify_on_fail
      #- notify_on_pass

  build-backend:
    <<: *nodeDockerImage
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend && npm install && npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - notify_on_fail
      - notify_on_pass
  
  test-frontend:
    <<: *nodeDockerImage
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Run frontend test
          command: |
             cd frontend && npm install && npm run test

  test-backend:
    <<: *nodeDockerImage
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Run backend test
          command: |
             cd backend && npm install && npm run test

  scan-frontend:
    <<: *nodeDockerImage
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Run frontend scan
          command: |
             cd frontend && npm install && npm audit fix --audit-level=critical --force

  scan-backend:
    <<: *nodeDockerImage
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Run backend scan
          command: |
             cd backend && npm install && npm audit fix --audit-level=critical --force

  deploy-infrastructure:
    <<: *awsDockerImage
    steps:
      - checkout
      - run:
          name: Install tar and gzip utilities
          command: |
            yum install -y tar gzip
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:project,Values=udapeople" \
            --output text >> ~/project/.circleci/ansible/inventory.txt
      - run:
          name: Display server-ip content (IP Added)
          command: |
            cat ~/project/.circleci/ansible/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      
      # Here's where you will add some code to rollback on failure 
      - destroy-environment:
          backendStackName: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
          frontendStackName: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"

  configure-infrastructure:
    <<: *pythonDockerImage
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["a2:ef:6c:6c:b4:4f:6f:1b:2a:6c:b1:5e:b3:e5:dd:03"] 
      # Attach workspace
      - attach_workspace:
          at: ~/
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install ansible && pip install awscli
      - run:
          name: Configure server
          command: |
            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
      
      # Here's where you will add some code to rollback on failure
      - destroy-environment:
          backendStackName: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
          frontendStackName: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"

  run-migrations:
    <<: *nodeAndAwsDockerImage
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            cd backend && npm install && npm run migrations > migrations_dump.txt
          no_output_timeout: 20m
      - run: cd backend && echo "has been executed successfully." > migrations_dump.txt
      - run:
          name: Send migration results to kvdb
          command: |
            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
            then
                curl -k https://kvdb.io/HdG73edBCgRpvJUzE1UP52/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
            fi
      
      # Here's where you will add some code to rollback on failure
      - destroy-environment:
          backendStackName: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
          frontendStackName: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"

  deploy-frontend:
    <<: *awsDockerImage
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum install -y tar gzip ansible python3 nodejs npm
      # Attach workspace
      - attach_workspace:
          at: ~/
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:project,Values=udapeople" \
            --output text)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL=${API_URL}"
            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            cat frontend/.env
      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            npm install
            npm run build
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
      
      # Here's where you will add some code to rollback on failure
      - destroy-environment:
          backendStackName: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
          frontendStackName: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"

  deploy-backend:
    <<: *pythonDockerImage
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["a2:ef:6c:6c:b4:4f:6f:1b:2a:6c:b1:5e:b3:e5:dd:03"] 
      # Attach workspace
      - attach_workspace:
          at: ~/
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install ansible && pip install awscli
      - run:
          name: Deploy backend
          command: |
            cd backend
            npm i
            npm run build
            cd ..
            # Zip the directory
            tar -C backend -czvf artifact.tar.gz .
            cd .circleci/ansible
            echo "Contents  of the ~/project/.circleci/ansible/inventory.txt file is -------"
            cat inventory.txt
            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt deploy-backend.yml
      
      # Here's where you will add some code to rollback on failure
      - destroy-environment:
          backendStackName: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
          frontendStackName: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
  
workflows:
  default:
    jobs:
      - build-frontend:
          context: org-global-udapeople
      - build-backend:
          context: org-global-udapeople
      - test-frontend:
          context: org-global-udapeople
          requires: [build-frontend]
      - test-backend:
          context: org-global-udapeople
          requires: [build-backend]
      - scan-frontend:
          context: org-global-udapeople
          requires: [build-frontend]
      - scan-backend:
          context: org-global-udapeople
          requires: [build-backend]
      - deploy-infrastructure:
          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [master]
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - run-migrations:
          requires: [configure-infrastructure]
      - deploy-frontend:
          requires: [run-migrations]
      - deploy-backend:
          requires: [run-migrations]
